# Generated by Django 3.2.1 on 2021-05-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialissuecomments',
            name='social_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.socialissue'),
        ),
        migrations.AlterField(
            model_name='socialissuelikes',
            name='social_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.socialissue'),
        ),
    ]
