# Generated by Django 3.2.1 on 2021-05-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210508_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialissue',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
