# Generated by Django 3.2.1 on 2021-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_socialissue_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialissuecomments',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socialissuelikes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
